//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWebApi.Order.Service.WcfOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class OrderModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.Order.Service.WcfOrderService.WcfOrder[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.Order.Service.WcfOrderService.WcfOrder[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfOrder", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class WcfOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AndroidEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AucIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AucRootTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarFirstImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarOverTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmissionStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FanLiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GatheringTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GearStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSXTPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NlTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NonlocalTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatus1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SearIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerConfirmTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketWinPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalBidCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VIPSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VipLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VipMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VoucherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WayTagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AndroidEndTime {
            get {
                return this.AndroidEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AndroidEndTimeField, value) != true)) {
                    this.AndroidEndTimeField = value;
                    this.RaisePropertyChanged("AndroidEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AucId {
            get {
                return this.AucIdField;
            }
            set {
                if ((this.AucIdField.Equals(value) != true)) {
                    this.AucIdField = value;
                    this.RaisePropertyChanged("AucId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AucRootTag {
            get {
                return this.AucRootTagField;
            }
            set {
                if ((this.AucRootTagField.Equals(value) != true)) {
                    this.AucRootTagField = value;
                    this.RaisePropertyChanged("AucRootTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.BeginTimeField, value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarFirstImg {
            get {
                return this.CarFirstImgField;
            }
            set {
                if ((object.ReferenceEquals(this.CarFirstImgField, value) != true)) {
                    this.CarFirstImgField = value;
                    this.RaisePropertyChanged("CarFirstImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarOverTime {
            get {
                return this.CarOverTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarOverTimeField, value) != true)) {
                    this.CarOverTimeField = value;
                    this.RaisePropertyChanged("CarOverTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedField, value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmissionStandard {
            get {
                return this.EmissionStandardField;
            }
            set {
                if ((object.ReferenceEquals(this.EmissionStandardField, value) != true)) {
                    this.EmissionStandardField = value;
                    this.RaisePropertyChanged("EmissionStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanLi {
            get {
                return this.FanLiField;
            }
            set {
                if ((this.FanLiField.Equals(value) != true)) {
                    this.FanLiField = value;
                    this.RaisePropertyChanged("FanLi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalOffer {
            get {
                return this.FinalOfferField;
            }
            set {
                if ((this.FinalOfferField.Equals(value) != true)) {
                    this.FinalOfferField = value;
                    this.RaisePropertyChanged("FinalOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatheringTime {
            get {
                return this.GatheringTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.GatheringTimeField, value) != true)) {
                    this.GatheringTimeField = value;
                    this.RaisePropertyChanged("GatheringTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GearStatus {
            get {
                return this.GearStatusField;
            }
            set {
                if ((this.GearStatusField.Equals(value) != true)) {
                    this.GearStatusField = value;
                    this.RaisePropertyChanged("GearStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSXTPaid {
            get {
                return this.IsSXTPaidField;
            }
            set {
                if ((this.IsSXTPaidField.Equals(value) != true)) {
                    this.IsSXTPaidField = value;
                    this.RaisePropertyChanged("IsSXTPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicHead {
            get {
                return this.LicHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.LicHeadField, value) != true)) {
                    this.LicHeadField = value;
                    this.RaisePropertyChanged("LicHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string License {
            get {
                return this.LicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseField, value) != true)) {
                    this.LicenseField = value;
                    this.RaisePropertyChanged("License");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NlTag {
            get {
                return this.NlTagField;
            }
            set {
                if ((this.NlTagField.Equals(value) != true)) {
                    this.NlTagField = value;
                    this.RaisePropertyChanged("NlTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NonlocalTag {
            get {
                return this.NonlocalTagField;
            }
            set {
                if ((this.NonlocalTagField.Equals(value) != true)) {
                    this.NonlocalTagField = value;
                    this.RaisePropertyChanged("NonlocalTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus1 {
            get {
                return this.OrderStatus1Field;
            }
            set {
                if ((this.OrderStatus1Field.Equals(value) != true)) {
                    this.OrderStatus1Field = value;
                    this.RaisePropertyChanged("OrderStatus1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgName {
            get {
                return this.OrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgNameField, value) != true)) {
                    this.OrgNameField = value;
                    this.RaisePropertyChanged("OrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegDateField, value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SearId {
            get {
                return this.SearIdField;
            }
            set {
                if ((this.SearIdField.Equals(value) != true)) {
                    this.SearIdField = value;
                    this.RaisePropertyChanged("SearId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellerConfirmTime {
            get {
                return this.SellerConfirmTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerConfirmTimeField, value) != true)) {
                    this.SellerConfirmTimeField = value;
                    this.RaisePropertyChanged("SellerConfirmTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketWinPrice {
            get {
                return this.TicketWinPriceField;
            }
            set {
                if ((this.TicketWinPriceField.Equals(value) != true)) {
                    this.TicketWinPriceField = value;
                    this.RaisePropertyChanged("TicketWinPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalBidCount {
            get {
                return this.TotalBidCountField;
            }
            set {
                if ((this.TotalBidCountField.Equals(value) != true)) {
                    this.TotalBidCountField = value;
                    this.RaisePropertyChanged("TotalBidCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode {
            get {
                return this.TradeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeCodeField, value) != true)) {
                    this.TradeCodeField = value;
                    this.RaisePropertyChanged("TradeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VIPSource {
            get {
                return this.VIPSourceField;
            }
            set {
                if ((this.VIPSourceField.Equals(value) != true)) {
                    this.VIPSourceField = value;
                    this.RaisePropertyChanged("VIPSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VipLevel {
            get {
                return this.VipLevelField;
            }
            set {
                if ((this.VipLevelField.Equals(value) != true)) {
                    this.VipLevelField = value;
                    this.RaisePropertyChanged("VipLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VipMoney {
            get {
                return this.VipMoneyField;
            }
            set {
                if ((this.VipMoneyField.Equals(value) != true)) {
                    this.VipMoneyField = value;
                    this.RaisePropertyChanged("VipMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Voucher {
            get {
                return this.VoucherField;
            }
            set {
                if ((this.VoucherField.Equals(value) != true)) {
                    this.VoucherField = value;
                    this.RaisePropertyChanged("Voucher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WayTag {
            get {
                return this.WayTagField;
            }
            set {
                if ((this.WayTagField.Equals(value) != true)) {
                    this.WayTagField = value;
                    this.RaisePropertyChanged("WayTag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class SearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.Order.Service.WcfOrderService.WcfSearch[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MsgReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MsgTimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Free {
            get {
                return this.FreeField;
            }
            set {
                if ((this.FreeField.Equals(value) != true)) {
                    this.FreeField = value;
                    this.RaisePropertyChanged("Free");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.Order.Service.WcfOrderService.WcfSearch[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MsgReturn {
            get {
                return this.MsgReturnField;
            }
            set {
                if ((this.MsgReturnField.Equals(value) != true)) {
                    this.MsgReturnField = value;
                    this.RaisePropertyChanged("MsgReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MsgTimes {
            get {
                return this.MsgTimesField;
            }
            set {
                if ((this.MsgTimesField.Equals(value) != true)) {
                    this.MsgTimesField = value;
                    this.RaisePropertyChanged("MsgTimes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfSearch", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class WcfSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarFirstImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CharacterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmissionStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PzGearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PzPlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PzTcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WayTagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acount {
            get {
                return this.AcountField;
            }
            set {
                if ((object.ReferenceEquals(this.AcountField, value) != true)) {
                    this.AcountField = value;
                    this.RaisePropertyChanged("Acount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarFirstImg {
            get {
                return this.CarFirstImgField;
            }
            set {
                if ((object.ReferenceEquals(this.CarFirstImgField, value) != true)) {
                    this.CarFirstImgField = value;
                    this.RaisePropertyChanged("CarFirstImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Character {
            get {
                return this.CharacterField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterField, value) != true)) {
                    this.CharacterField = value;
                    this.RaisePropertyChanged("Character");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmissionStandard {
            get {
                return this.EmissionStandardField;
            }
            set {
                if ((object.ReferenceEquals(this.EmissionStandardField, value) != true)) {
                    this.EmissionStandardField = value;
                    this.RaisePropertyChanged("EmissionStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string License {
            get {
                return this.LicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseField, value) != true)) {
                    this.LicenseField = value;
                    this.RaisePropertyChanged("License");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseModel {
            get {
                return this.LicenseModelField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseModelField, value) != true)) {
                    this.LicenseModelField = value;
                    this.RaisePropertyChanged("LicenseModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseType {
            get {
                return this.LicenseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseTypeField, value) != true)) {
                    this.LicenseTypeField = value;
                    this.RaisePropertyChanged("LicenseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PzGear {
            get {
                return this.PzGearField;
            }
            set {
                if ((object.ReferenceEquals(this.PzGearField, value) != true)) {
                    this.PzGearField = value;
                    this.RaisePropertyChanged("PzGear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PzPl {
            get {
                return this.PzPlField;
            }
            set {
                if ((object.ReferenceEquals(this.PzPlField, value) != true)) {
                    this.PzPlField = value;
                    this.RaisePropertyChanged("PzPl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PzTc {
            get {
                return this.PzTcField;
            }
            set {
                if ((object.ReferenceEquals(this.PzTcField, value) != true)) {
                    this.PzTcField = value;
                    this.RaisePropertyChanged("PzTc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegDateField, value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode {
            get {
                return this.TradeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeCodeField, value) != true)) {
                    this.TradeCodeField = value;
                    this.RaisePropertyChanged("TradeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeDate {
            get {
                return this.TradeDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeDateField, value) != true)) {
                    this.TradeDateField = value;
                    this.RaisePropertyChanged("TradeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WayTag {
            get {
                return this.WayTagField;
            }
            set {
                if ((this.WayTagField.Equals(value) != true)) {
                    this.WayTagField = value;
                    this.RaisePropertyChanged("WayTag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseListModelOfWcfCarOrder_S7WUFefR", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class BaseListModelOfWcfCarOrder_S7WUFefR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.Order.Service.WcfOrderService.WcfCarOrder[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.Order.Service.WcfOrderService.WcfCarOrder[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfCarOrder", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class WcfCarOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AucIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AucRootTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarFirstImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmissionStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FanLiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FanLiNonlocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalOfferNonlocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsFanliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NonlocalTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatorActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SellerConfirmTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketWinPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WayTagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AucId {
            get {
                return this.AucIdField;
            }
            set {
                if ((this.AucIdField.Equals(value) != true)) {
                    this.AucIdField = value;
                    this.RaisePropertyChanged("AucId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AucRootTag {
            get {
                return this.AucRootTagField;
            }
            set {
                if ((this.AucRootTagField.Equals(value) != true)) {
                    this.AucRootTagField = value;
                    this.RaisePropertyChanged("AucRootTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarFirstImg {
            get {
                return this.CarFirstImgField;
            }
            set {
                if ((object.ReferenceEquals(this.CarFirstImgField, value) != true)) {
                    this.CarFirstImgField = value;
                    this.RaisePropertyChanged("CarFirstImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmissionStandard {
            get {
                return this.EmissionStandardField;
            }
            set {
                if ((object.ReferenceEquals(this.EmissionStandardField, value) != true)) {
                    this.EmissionStandardField = value;
                    this.RaisePropertyChanged("EmissionStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanLi {
            get {
                return this.FanLiField;
            }
            set {
                if ((this.FanLiField.Equals(value) != true)) {
                    this.FanLiField = value;
                    this.RaisePropertyChanged("FanLi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanLiNonlocal {
            get {
                return this.FanLiNonlocalField;
            }
            set {
                if ((this.FanLiNonlocalField.Equals(value) != true)) {
                    this.FanLiNonlocalField = value;
                    this.RaisePropertyChanged("FanLiNonlocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalOffer {
            get {
                return this.FinalOfferField;
            }
            set {
                if ((this.FinalOfferField.Equals(value) != true)) {
                    this.FinalOfferField = value;
                    this.RaisePropertyChanged("FinalOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalOfferNonlocal {
            get {
                return this.FinalOfferNonlocalField;
            }
            set {
                if ((this.FinalOfferNonlocalField.Equals(value) != true)) {
                    this.FinalOfferNonlocalField = value;
                    this.RaisePropertyChanged("FinalOfferNonlocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsFanli {
            get {
                return this.IsFanliField;
            }
            set {
                if ((this.IsFanliField.Equals(value) != true)) {
                    this.IsFanliField = value;
                    this.RaisePropertyChanged("IsFanli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string License {
            get {
                return this.LicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseField, value) != true)) {
                    this.LicenseField = value;
                    this.RaisePropertyChanged("License");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseModel {
            get {
                return this.LicenseModelField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseModelField, value) != true)) {
                    this.LicenseModelField = value;
                    this.RaisePropertyChanged("LicenseModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NonlocalTag {
            get {
                return this.NonlocalTagField;
            }
            set {
                if ((this.NonlocalTagField.Equals(value) != true)) {
                    this.NonlocalTagField = value;
                    this.RaisePropertyChanged("NonlocalTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatorAct {
            get {
                return this.OperatorActField;
            }
            set {
                if ((this.OperatorActField.Equals(value) != true)) {
                    this.OperatorActField = value;
                    this.RaisePropertyChanged("OperatorAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegArea {
            get {
                return this.RegAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.RegAreaField, value) != true)) {
                    this.RegAreaField = value;
                    this.RaisePropertyChanged("RegArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegDateField, value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleTag {
            get {
                return this.SaleTagField;
            }
            set {
                if ((this.SaleTagField.Equals(value) != true)) {
                    this.SaleTagField = value;
                    this.RaisePropertyChanged("SaleTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SellerConfirmTime {
            get {
                return this.SellerConfirmTimeField;
            }
            set {
                if ((this.SellerConfirmTimeField.Equals(value) != true)) {
                    this.SellerConfirmTimeField = value;
                    this.RaisePropertyChanged("SellerConfirmTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketWinPrice {
            get {
                return this.TicketWinPriceField;
            }
            set {
                if ((this.TicketWinPriceField.Equals(value) != true)) {
                    this.TicketWinPriceField = value;
                    this.RaisePropertyChanged("TicketWinPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode {
            get {
                return this.TradeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeCodeField, value) != true)) {
                    this.TradeCodeField = value;
                    this.RaisePropertyChanged("TradeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WayTag {
            get {
                return this.WayTagField;
            }
            set {
                if ((this.WayTagField.Equals(value) != true)) {
                    this.WayTagField = value;
                    this.RaisePropertyChanged("WayTag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfOrderService.IWcfOrderService")]
    public interface IWcfOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetDealCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetDealCarListResponse")]
        MobileWebApi.Order.Service.WcfOrderService.OrderModel GetDealCarList(int userId, int orderStatus, int isThisYear, string model, int islongbid, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetDealCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetDealCarListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.OrderModel> GetDealCarListAsync(int userId, int orderStatus, int isThisYear, string model, int islongbid, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetCarPriceSearchList", ReplyAction="http://tempuri.org/IWcfOrderService/GetCarPriceSearchListResponse")]
        MobileWebApi.Order.Service.WcfOrderService.SearchModel GetCarPriceSearchList(int businessId, int buyerLevel, int orid, int countryId, string brand, string mf, string series, int pzgear, int topNum, int isSeries, string tokenKey, string emissionStandard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetCarPriceSearchList", ReplyAction="http://tempuri.org/IWcfOrderService/GetCarPriceSearchListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.SearchModel> GetCarPriceSearchListAsync(int businessId, int buyerLevel, int orid, int countryId, string brand, string mf, string series, int pzgear, int topNum, int isSeries, string tokenKey, string emissionStandard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetTradeoffMsg", ReplyAction="http://tempuri.org/IWcfOrderService/GetTradeoffMsgResponse")]
        string GetTradeoffMsg(string orderId, int aucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetTradeoffMsg", ReplyAction="http://tempuri.org/IWcfOrderService/GetTradeoffMsgResponse")]
        System.Threading.Tasks.Task<string> GetTradeoffMsgAsync(string orderId, int aucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetUnConfirmCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetUnConfirmCarListResponse")]
        MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetUnConfirmCarList(int businessId, int aucRootTag, string searchTxt, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetUnConfirmCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetUnConfirmCarListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetUnConfirmCarListAsync(int businessId, int aucRootTag, string searchTxt, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetOrderCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetOrderCarListResponse")]
        MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetOrderCarList(int businessId, int rootTag, int orderStatus, int markTime, string searchTxt, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetOrderCarList", ReplyAction="http://tempuri.org/IWcfOrderService/GetOrderCarListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetOrderCarListAsync(int businessId, int rootTag, int orderStatus, int markTime, string searchTxt, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetBidHistoryList", ReplyAction="http://tempuri.org/IWcfOrderService/GetBidHistoryListResponse")]
        MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetBidHistoryList(int businessId, int aucRootTag, int markTime, int caseType, string searchTxt, int pageSize, int pageIndex, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfOrderService/GetBidHistoryList", ReplyAction="http://tempuri.org/IWcfOrderService/GetBidHistoryListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetBidHistoryListAsync(int businessId, int aucRootTag, int markTime, int caseType, string searchTxt, int pageSize, int pageIndex, string tokenKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfOrderServiceChannel : global::MobileWebApi.Order.Service.WcfOrderService.IWcfOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfOrderServiceClient : System.ServiceModel.ClientBase<global::MobileWebApi.Order.Service.WcfOrderService.IWcfOrderService>, global::MobileWebApi.Order.Service.WcfOrderService.IWcfOrderService {
        
        public WcfOrderServiceClient() {
        }
        
        public WcfOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MobileWebApi.Order.Service.WcfOrderService.OrderModel GetDealCarList(int userId, int orderStatus, int isThisYear, string model, int islongbid, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetDealCarList(userId, orderStatus, isThisYear, model, islongbid, pageSize, pageIndex, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.OrderModel> GetDealCarListAsync(int userId, int orderStatus, int isThisYear, string model, int islongbid, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetDealCarListAsync(userId, orderStatus, isThisYear, model, islongbid, pageSize, pageIndex, tokenKey);
        }
        
        public MobileWebApi.Order.Service.WcfOrderService.SearchModel GetCarPriceSearchList(int businessId, int buyerLevel, int orid, int countryId, string brand, string mf, string series, int pzgear, int topNum, int isSeries, string tokenKey, string emissionStandard) {
            return base.Channel.GetCarPriceSearchList(businessId, buyerLevel, orid, countryId, brand, mf, series, pzgear, topNum, isSeries, tokenKey, emissionStandard);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.SearchModel> GetCarPriceSearchListAsync(int businessId, int buyerLevel, int orid, int countryId, string brand, string mf, string series, int pzgear, int topNum, int isSeries, string tokenKey, string emissionStandard) {
            return base.Channel.GetCarPriceSearchListAsync(businessId, buyerLevel, orid, countryId, brand, mf, series, pzgear, topNum, isSeries, tokenKey, emissionStandard);
        }
        
        public string GetTradeoffMsg(string orderId, int aucId) {
            return base.Channel.GetTradeoffMsg(orderId, aucId);
        }
        
        public System.Threading.Tasks.Task<string> GetTradeoffMsgAsync(string orderId, int aucId) {
            return base.Channel.GetTradeoffMsgAsync(orderId, aucId);
        }
        
        public MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetUnConfirmCarList(int businessId, int aucRootTag, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetUnConfirmCarList(businessId, aucRootTag, searchTxt, pageSize, pageIndex, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetUnConfirmCarListAsync(int businessId, int aucRootTag, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetUnConfirmCarListAsync(businessId, aucRootTag, searchTxt, pageSize, pageIndex, tokenKey);
        }
        
        public MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetOrderCarList(int businessId, int rootTag, int orderStatus, int markTime, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetOrderCarList(businessId, rootTag, orderStatus, markTime, searchTxt, pageSize, pageIndex, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetOrderCarListAsync(int businessId, int rootTag, int orderStatus, int markTime, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetOrderCarListAsync(businessId, rootTag, orderStatus, markTime, searchTxt, pageSize, pageIndex, tokenKey);
        }
        
        public MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR GetBidHistoryList(int businessId, int aucRootTag, int markTime, int caseType, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetBidHistoryList(businessId, aucRootTag, markTime, caseType, searchTxt, pageSize, pageIndex, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.Order.Service.WcfOrderService.BaseListModelOfWcfCarOrder_S7WUFefR> GetBidHistoryListAsync(int businessId, int aucRootTag, int markTime, int caseType, string searchTxt, int pageSize, int pageIndex, string tokenKey) {
            return base.Channel.GetBidHistoryListAsync(businessId, aucRootTag, markTime, caseType, searchTxt, pageSize, pageIndex, tokenKey);
        }
    }
}
