//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWebApi.User.Service.UserWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccountModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class UserAccountModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlanceMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FreezeCarNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FreezeMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMoneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlanceMoney {
            get {
                return this.BlanceMoneyField;
            }
            set {
                if ((this.BlanceMoneyField.Equals(value) != true)) {
                    this.BlanceMoneyField = value;
                    this.RaisePropertyChanged("BlanceMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreezeCarNum {
            get {
                return this.FreezeCarNumField;
            }
            set {
                if ((this.FreezeCarNumField.Equals(value) != true)) {
                    this.FreezeCarNumField = value;
                    this.RaisePropertyChanged("FreezeCarNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreezeMoney {
            get {
                return this.FreezeMoneyField;
            }
            set {
                if ((this.FreezeMoneyField.Equals(value) != true)) {
                    this.FreezeMoneyField = value;
                    this.RaisePropertyChanged("FreezeMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMoney {
            get {
                return this.TotalMoneyField;
            }
            set {
                if ((this.TotalMoneyField.Equals(value) != true)) {
                    this.TotalMoneyField = value;
                    this.RaisePropertyChanged("TotalMoney");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseListModelOfEarnestModel_S7WUFefR", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class BaseListModelOfEarnestModel_S7WUFefR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.User.Service.UserWcfService.EarnestModel[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.User.Service.UserWcfService.EarnestModel[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EarnestModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class EarnestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransWayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransContent {
            get {
                return this.TransContentField;
            }
            set {
                if ((object.ReferenceEquals(this.TransContentField, value) != true)) {
                    this.TransContentField = value;
                    this.RaisePropertyChanged("TransContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransDate {
            get {
                return this.TransDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransDateField, value) != true)) {
                    this.TransDateField = value;
                    this.RaisePropertyChanged("TransDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransNum {
            get {
                return this.TransNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TransNumField, value) != true)) {
                    this.TransNumField = value;
                    this.RaisePropertyChanged("TransNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransStatus {
            get {
                return this.TransStatusField;
            }
            set {
                if ((this.TransStatusField.Equals(value) != true)) {
                    this.TransStatusField = value;
                    this.RaisePropertyChanged("TransStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransWay {
            get {
                return this.TransWayField;
            }
            set {
                if ((this.TransWayField.Equals(value) != true)) {
                    this.TransWayField = value;
                    this.RaisePropertyChanged("TransWay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class VoucherModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContributeVoucherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenContributeVoucherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GeneralVoucherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContributeVoucher {
            get {
                return this.ContributeVoucherField;
            }
            set {
                if ((this.ContributeVoucherField.Equals(value) != true)) {
                    this.ContributeVoucherField = value;
                    this.RaisePropertyChanged("ContributeVoucher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenContributeVoucher {
            get {
                return this.GenContributeVoucherField;
            }
            set {
                if ((this.GenContributeVoucherField.Equals(value) != true)) {
                    this.GenContributeVoucherField = value;
                    this.RaisePropertyChanged("GenContributeVoucher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GeneralVoucher {
            get {
                return this.GeneralVoucherField;
            }
            set {
                if ((this.GeneralVoucherField.Equals(value) != true)) {
                    this.GeneralVoucherField = value;
                    this.RaisePropertyChanged("GeneralVoucher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseListModelOfVoucherListModel_S7WUFefR", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class BaseListModelOfVoucherListModel_S7WUFefR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.User.Service.UserWcfService.VoucherListModel[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.User.Service.UserWcfService.VoucherListModel[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherListModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class VoucherListModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransContent {
            get {
                return this.TransContentField;
            }
            set {
                if ((object.ReferenceEquals(this.TransContentField, value) != true)) {
                    this.TransContentField = value;
                    this.RaisePropertyChanged("TransContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransDate {
            get {
                return this.TransDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransDateField, value) != true)) {
                    this.TransDateField = value;
                    this.RaisePropertyChanged("TransDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransNum {
            get {
                return this.TransNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TransNumField, value) != true)) {
                    this.TransNumField = value;
                    this.RaisePropertyChanged("TransNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusSxtModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class BusSxtModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IfSXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeftLoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalLoanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IfSXT {
            get {
                return this.IfSXTField;
            }
            set {
                if ((this.IfSXTField.Equals(value) != true)) {
                    this.IfSXTField = value;
                    this.RaisePropertyChanged("IfSXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeftLoan {
            get {
                return this.LeftLoanField;
            }
            set {
                if ((this.LeftLoanField.Equals(value) != true)) {
                    this.LeftLoanField = value;
                    this.RaisePropertyChanged("LeftLoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalLoan {
            get {
                return this.TotalLoanField;
            }
            set {
                if ((this.TotalLoanField.Equals(value) != true)) {
                    this.TotalLoanField = value;
                    this.RaisePropertyChanged("TotalLoan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseListModelOfSxtListModel_S7WUFefR", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class BaseListModelOfSxtListModel_S7WUFefR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileWebApi.User.Service.UserWcfService.SxtListModel[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileWebApi.User.Service.UserWcfService.SxtListModel[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SxtListModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class SxtListModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AucIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarFirstImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarRegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmissionStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpireTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FanLiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IfExceedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsLongBidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NlTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RealVoucherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerConfirmTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketWinPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VoucherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WayTagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AucId {
            get {
                return this.AucIdField;
            }
            set {
                if ((this.AucIdField.Equals(value) != true)) {
                    this.AucIdField = value;
                    this.RaisePropertyChanged("AucId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarFirstImg {
            get {
                return this.CarFirstImgField;
            }
            set {
                if ((object.ReferenceEquals(this.CarFirstImgField, value) != true)) {
                    this.CarFirstImgField = value;
                    this.RaisePropertyChanged("CarFirstImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarRegDate {
            get {
                return this.CarRegDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CarRegDateField, value) != true)) {
                    this.CarRegDateField = value;
                    this.RaisePropertyChanged("CarRegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmissionStandard {
            get {
                return this.EmissionStandardField;
            }
            set {
                if ((object.ReferenceEquals(this.EmissionStandardField, value) != true)) {
                    this.EmissionStandardField = value;
                    this.RaisePropertyChanged("EmissionStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpireTime {
            get {
                return this.ExpireTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpireTimeField, value) != true)) {
                    this.ExpireTimeField = value;
                    this.RaisePropertyChanged("ExpireTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanLi {
            get {
                return this.FanLiField;
            }
            set {
                if ((this.FanLiField.Equals(value) != true)) {
                    this.FanLiField = value;
                    this.RaisePropertyChanged("FanLi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalOffer {
            get {
                return this.FinalOfferField;
            }
            set {
                if ((this.FinalOfferField.Equals(value) != true)) {
                    this.FinalOfferField = value;
                    this.RaisePropertyChanged("FinalOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IfExceed {
            get {
                return this.IfExceedField;
            }
            set {
                if ((this.IfExceedField.Equals(value) != true)) {
                    this.IfExceedField = value;
                    this.RaisePropertyChanged("IfExceed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsLongBid {
            get {
                return this.IsLongBidField;
            }
            set {
                if ((this.IsLongBidField.Equals(value) != true)) {
                    this.IsLongBidField = value;
                    this.RaisePropertyChanged("IsLongBid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((this.LastDateField.Equals(value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((object.ReferenceEquals(this.MileageField, value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NlTag {
            get {
                return this.NlTagField;
            }
            set {
                if ((this.NlTagField.Equals(value) != true)) {
                    this.NlTagField = value;
                    this.RaisePropertyChanged("NlTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgName {
            get {
                return this.OrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgNameField, value) != true)) {
                    this.OrgNameField = value;
                    this.RaisePropertyChanged("OrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RealVoucher {
            get {
                return this.RealVoucherField;
            }
            set {
                if ((this.RealVoucherField.Equals(value) != true)) {
                    this.RealVoucherField = value;
                    this.RaisePropertyChanged("RealVoucher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellerConfirmTime {
            get {
                return this.SellerConfirmTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerConfirmTimeField, value) != true)) {
                    this.SellerConfirmTimeField = value;
                    this.RaisePropertyChanged("SellerConfirmTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketWinPrice {
            get {
                return this.TicketWinPriceField;
            }
            set {
                if ((this.TicketWinPriceField.Equals(value) != true)) {
                    this.TicketWinPriceField = value;
                    this.RaisePropertyChanged("TicketWinPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode {
            get {
                return this.TradeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeCodeField, value) != true)) {
                    this.TradeCodeField = value;
                    this.RaisePropertyChanged("TradeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Voucher {
            get {
                return this.VoucherField;
            }
            set {
                if ((this.VoucherField.Equals(value) != true)) {
                    this.VoucherField = value;
                    this.RaisePropertyChanged("Voucher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WayTag {
            get {
                return this.WayTagField;
            }
            set {
                if ((this.WayTagField.Equals(value) != true)) {
                    this.WayTagField = value;
                    this.RaisePropertyChanged("WayTag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeadImgModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class HeadImgModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadImgUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadImg {
            get {
                return this.HeadImgField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadImgField, value) != true)) {
                    this.HeadImgField = value;
                    this.RaisePropertyChanged("HeadImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadImgUrl {
            get {
                return this.HeadImgUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadImgUrlField, value) != true)) {
                    this.HeadImgUrlField = value;
                    this.RaisePropertyChanged("HeadImgUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsTypeModel", Namespace="http://schemas.datacontract.org/2004/07/CYP2014.Shd.WCF.Service.Models")]
    [System.SerializableAttribute()]
    public partial class SmsTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmsTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSend {
            get {
                return this.IsSendField;
            }
            set {
                if ((this.IsSendField.Equals(value) != true)) {
                    this.IsSendField = value;
                    this.RaisePropertyChanged("IsSend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SmsType {
            get {
                return this.SmsTypeField;
            }
            set {
                if ((this.SmsTypeField.Equals(value) != true)) {
                    this.SmsTypeField = value;
                    this.RaisePropertyChanged("SmsType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWcfService.IUserSerWCF")]
    public interface IUserSerWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/DoWork", ReplyAction="http://tempuri.org/IUserSerWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/DoWork", ReplyAction="http://tempuri.org/IUserSerWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/AddUser", ReplyAction="http://tempuri.org/IUserSerWCF/AddUserResponse")]
        int AddUser(string businessId, string companyName, string isCompany, string provinceName, string cityName, string areaName, string areaId, string realName, string phone, string userName, string userPass, string agreementId, string cilentType, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/AddUser", ReplyAction="http://tempuri.org/IUserSerWCF/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string businessId, string companyName, string isCompany, string provinceName, string cityName, string areaName, string areaId, string realName, string phone, string userName, string userPass, string agreementId, string cilentType, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/ResetPassword", ReplyAction="http://tempuri.org/IUserSerWCF/ResetPasswordResponse")]
        string ResetPassword(string userName, string phone, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/ResetPassword", ReplyAction="http://tempuri.org/IUserSerWCF/ResetPasswordResponse")]
        System.Threading.Tasks.Task<string> ResetPasswordAsync(string userName, string phone, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/ModifyPwd", ReplyAction="http://tempuri.org/IUserSerWCF/ModifyPwdResponse")]
        string ModifyPwd(int businessId, string oldPwd, string newPwd, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/ModifyPwd", ReplyAction="http://tempuri.org/IUserSerWCF/ModifyPwdResponse")]
        System.Threading.Tasks.Task<string> ModifyPwdAsync(int businessId, string oldPwd, string newPwd, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/IsExistsUserName", ReplyAction="http://tempuri.org/IUserSerWCF/IsExistsUserNameResponse")]
        bool IsExistsUserName(string userName, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/IsExistsUserName", ReplyAction="http://tempuri.org/IUserSerWCF/IsExistsUserNameResponse")]
        System.Threading.Tasks.Task<bool> IsExistsUserNameAsync(string userName, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetEarnest", ReplyAction="http://tempuri.org/IUserSerWCF/GetEarnestResponse")]
        MobileWebApi.User.Service.UserWcfService.UserAccountModel GetEarnest(string uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetEarnest", ReplyAction="http://tempuri.org/IUserSerWCF/GetEarnestResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.UserAccountModel> GetEarnestAsync(string uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetEarnestLog", ReplyAction="http://tempuri.org/IUserSerWCF/GetEarnestLogResponse")]
        MobileWebApi.User.Service.UserWcfService.BaseListModelOfEarnestModel_S7WUFefR GetEarnestLog(string uid, System.DateTime beginTime, int tag, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetEarnestLog", ReplyAction="http://tempuri.org/IUserSerWCF/GetEarnestLogResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfEarnestModel_S7WUFefR> GetEarnestLogAsync(string uid, System.DateTime beginTime, int tag, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetVoucherInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetVoucherInfoResponse")]
        MobileWebApi.User.Service.UserWcfService.VoucherModel GetVoucherInfo(string uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetVoucherInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetVoucherInfoResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.VoucherModel> GetVoucherInfoAsync(string uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetVoucherList", ReplyAction="http://tempuri.org/IUserSerWCF/GetVoucherListResponse")]
        MobileWebApi.User.Service.UserWcfService.BaseListModelOfVoucherListModel_S7WUFefR GetVoucherList(int uid, int type, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetVoucherList", ReplyAction="http://tempuri.org/IUserSerWCF/GetVoucherListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfVoucherListModel_S7WUFefR> GetVoucherListAsync(int uid, int type, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetUserSxtInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetUserSxtInfoResponse")]
        MobileWebApi.User.Service.UserWcfService.BusSxtModel GetUserSxtInfo(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetUserSxtInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetUserSxtInfoResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BusSxtModel> GetUserSxtInfoAsync(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetSxtList", ReplyAction="http://tempuri.org/IUserSerWCF/GetSxtListResponse")]
        MobileWebApi.User.Service.UserWcfService.BaseListModelOfSxtListModel_S7WUFefR GetSxtList(int uid, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetSxtList", ReplyAction="http://tempuri.org/IUserSerWCF/GetSxtListResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfSxtListModel_S7WUFefR> GetSxtListAsync(int uid, int pageIndex, int pageSize, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetHeadImgInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetHeadImgInfoResponse")]
        MobileWebApi.User.Service.UserWcfService.HeadImgModel GetHeadImgInfo(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetHeadImgInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetHeadImgInfoResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.HeadImgModel> GetHeadImgInfoAsync(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetSmsSettingInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetSmsSettingInfoResponse")]
        MobileWebApi.User.Service.UserWcfService.SmsTypeModel[] GetSmsSettingInfo(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/GetSmsSettingInfo", ReplyAction="http://tempuri.org/IUserSerWCF/GetSmsSettingInfoResponse")]
        System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.SmsTypeModel[]> GetSmsSettingInfoAsync(int uid, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/SaveSmsSetting", ReplyAction="http://tempuri.org/IUserSerWCF/SaveSmsSettingResponse")]
        bool SaveSmsSetting(int uid, int cjdx, int jytzdx, int jysbdx, int spdx, string tokenKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSerWCF/SaveSmsSetting", ReplyAction="http://tempuri.org/IUserSerWCF/SaveSmsSettingResponse")]
        System.Threading.Tasks.Task<bool> SaveSmsSettingAsync(int uid, int cjdx, int jytzdx, int jysbdx, int spdx, string tokenKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserSerWCFChannel : MobileWebApi.User.Service.UserWcfService.IUserSerWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSerWCFClient : System.ServiceModel.ClientBase<MobileWebApi.User.Service.UserWcfService.IUserSerWCF>, MobileWebApi.User.Service.UserWcfService.IUserSerWCF {
        
        public UserSerWCFClient() {
        }
        
        public UserSerWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSerWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSerWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSerWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int AddUser(string businessId, string companyName, string isCompany, string provinceName, string cityName, string areaName, string areaId, string realName, string phone, string userName, string userPass, string agreementId, string cilentType, string tokenKey) {
            return base.Channel.AddUser(businessId, companyName, isCompany, provinceName, cityName, areaName, areaId, realName, phone, userName, userPass, agreementId, cilentType, tokenKey);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string businessId, string companyName, string isCompany, string provinceName, string cityName, string areaName, string areaId, string realName, string phone, string userName, string userPass, string agreementId, string cilentType, string tokenKey) {
            return base.Channel.AddUserAsync(businessId, companyName, isCompany, provinceName, cityName, areaName, areaId, realName, phone, userName, userPass, agreementId, cilentType, tokenKey);
        }
        
        public string ResetPassword(string userName, string phone, string tokenKey) {
            return base.Channel.ResetPassword(userName, phone, tokenKey);
        }
        
        public System.Threading.Tasks.Task<string> ResetPasswordAsync(string userName, string phone, string tokenKey) {
            return base.Channel.ResetPasswordAsync(userName, phone, tokenKey);
        }
        
        public string ModifyPwd(int businessId, string oldPwd, string newPwd, string tokenKey) {
            return base.Channel.ModifyPwd(businessId, oldPwd, newPwd, tokenKey);
        }
        
        public System.Threading.Tasks.Task<string> ModifyPwdAsync(int businessId, string oldPwd, string newPwd, string tokenKey) {
            return base.Channel.ModifyPwdAsync(businessId, oldPwd, newPwd, tokenKey);
        }
        
        public bool IsExistsUserName(string userName, string tokenKey) {
            return base.Channel.IsExistsUserName(userName, tokenKey);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserNameAsync(string userName, string tokenKey) {
            return base.Channel.IsExistsUserNameAsync(userName, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.UserAccountModel GetEarnest(string uid, string tokenKey) {
            return base.Channel.GetEarnest(uid, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.UserAccountModel> GetEarnestAsync(string uid, string tokenKey) {
            return base.Channel.GetEarnestAsync(uid, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.BaseListModelOfEarnestModel_S7WUFefR GetEarnestLog(string uid, System.DateTime beginTime, int tag, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetEarnestLog(uid, beginTime, tag, pageIndex, pageSize, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfEarnestModel_S7WUFefR> GetEarnestLogAsync(string uid, System.DateTime beginTime, int tag, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetEarnestLogAsync(uid, beginTime, tag, pageIndex, pageSize, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.VoucherModel GetVoucherInfo(string uid, string tokenKey) {
            return base.Channel.GetVoucherInfo(uid, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.VoucherModel> GetVoucherInfoAsync(string uid, string tokenKey) {
            return base.Channel.GetVoucherInfoAsync(uid, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.BaseListModelOfVoucherListModel_S7WUFefR GetVoucherList(int uid, int type, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetVoucherList(uid, type, pageIndex, pageSize, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfVoucherListModel_S7WUFefR> GetVoucherListAsync(int uid, int type, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetVoucherListAsync(uid, type, pageIndex, pageSize, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.BusSxtModel GetUserSxtInfo(int uid, string tokenKey) {
            return base.Channel.GetUserSxtInfo(uid, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BusSxtModel> GetUserSxtInfoAsync(int uid, string tokenKey) {
            return base.Channel.GetUserSxtInfoAsync(uid, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.BaseListModelOfSxtListModel_S7WUFefR GetSxtList(int uid, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetSxtList(uid, pageIndex, pageSize, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.BaseListModelOfSxtListModel_S7WUFefR> GetSxtListAsync(int uid, int pageIndex, int pageSize, string tokenKey) {
            return base.Channel.GetSxtListAsync(uid, pageIndex, pageSize, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.HeadImgModel GetHeadImgInfo(int uid, string tokenKey) {
            return base.Channel.GetHeadImgInfo(uid, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.HeadImgModel> GetHeadImgInfoAsync(int uid, string tokenKey) {
            return base.Channel.GetHeadImgInfoAsync(uid, tokenKey);
        }
        
        public MobileWebApi.User.Service.UserWcfService.SmsTypeModel[] GetSmsSettingInfo(int uid, string tokenKey) {
            return base.Channel.GetSmsSettingInfo(uid, tokenKey);
        }
        
        public System.Threading.Tasks.Task<MobileWebApi.User.Service.UserWcfService.SmsTypeModel[]> GetSmsSettingInfoAsync(int uid, string tokenKey) {
            return base.Channel.GetSmsSettingInfoAsync(uid, tokenKey);
        }
        
        public bool SaveSmsSetting(int uid, int cjdx, int jytzdx, int jysbdx, int spdx, string tokenKey) {
            return base.Channel.SaveSmsSetting(uid, cjdx, jytzdx, jysbdx, spdx, tokenKey);
        }
        
        public System.Threading.Tasks.Task<bool> SaveSmsSettingAsync(int uid, int cjdx, int jytzdx, int jysbdx, int spdx, string tokenKey) {
            return base.Channel.SaveSmsSettingAsync(uid, cjdx, jytzdx, jysbdx, spdx, tokenKey);
        }
    }
}
