//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWebApi.Misc.Service.WcfPushService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfPushService.IPushSer")]
    public interface IPushSer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/DoWork", ReplyAction="http://tempuri.org/IPushSer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/DoWork", ReplyAction="http://tempuri.org/IPushSer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForPad", ReplyAction="http://tempuri.org/IPushSer/PushForPadResponse")]
        void PushForPad(string key, string msginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForPad", ReplyAction="http://tempuri.org/IPushSer/PushForPadResponse")]
        System.Threading.Tasks.Task PushForPadAsync(string key, string msginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForMobile", ReplyAction="http://tempuri.org/IPushSer/PushForMobileResponse")]
        void PushForMobile(string key, string msginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForMobile", ReplyAction="http://tempuri.org/IPushSer/PushForMobileResponse")]
        System.Threading.Tasks.Task PushForMobileAsync(string key, string msginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForPadLate", ReplyAction="http://tempuri.org/IPushSer/PushForPadLateResponse")]
        void PushForPadLate(string key, string msginfo, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForPadLate", ReplyAction="http://tempuri.org/IPushSer/PushForPadLateResponse")]
        System.Threading.Tasks.Task PushForPadLateAsync(string key, string msginfo, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForMobileLate", ReplyAction="http://tempuri.org/IPushSer/PushForMobileLateResponse")]
        void PushForMobileLate(string key, string msginfo, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushSer/PushForMobileLate", ReplyAction="http://tempuri.org/IPushSer/PushForMobileLateResponse")]
        System.Threading.Tasks.Task PushForMobileLateAsync(string key, string msginfo, System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushSerChannel : MobileWebApi.Misc.Service.WcfPushService.IPushSer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushSerClient : System.ServiceModel.ClientBase<MobileWebApi.Misc.Service.WcfPushService.IPushSer>, MobileWebApi.Misc.Service.WcfPushService.IPushSer {
        
        public PushSerClient() {
        }
        
        public PushSerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushSerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void PushForPad(string key, string msginfo) {
            base.Channel.PushForPad(key, msginfo);
        }
        
        public System.Threading.Tasks.Task PushForPadAsync(string key, string msginfo) {
            return base.Channel.PushForPadAsync(key, msginfo);
        }
        
        public void PushForMobile(string key, string msginfo) {
            base.Channel.PushForMobile(key, msginfo);
        }
        
        public System.Threading.Tasks.Task PushForMobileAsync(string key, string msginfo) {
            return base.Channel.PushForMobileAsync(key, msginfo);
        }
        
        public void PushForPadLate(string key, string msginfo, System.DateTime date) {
            base.Channel.PushForPadLate(key, msginfo, date);
        }
        
        public System.Threading.Tasks.Task PushForPadLateAsync(string key, string msginfo, System.DateTime date) {
            return base.Channel.PushForPadLateAsync(key, msginfo, date);
        }
        
        public void PushForMobileLate(string key, string msginfo, System.DateTime date) {
            base.Channel.PushForMobileLate(key, msginfo, date);
        }
        
        public System.Threading.Tasks.Task PushForMobileLateAsync(string key, string msginfo, System.DateTime date) {
            return base.Channel.PushForMobileLateAsync(key, msginfo, date);
        }
    }
}
